# Generated by Django 5.2.7 on 2025-11-16 15:55

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "uid",
                    models.CharField(
                        help_text="Unique device card UID (e.g: '12AB34567890DEAD').",
                        max_length=32,
                        unique=True,
                        verbose_name="device uid",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path of this card.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^(\\/dev\\/(tty(S|USB|ACM)[0-9]+|cu\\.[\\w\\-\\.]+)|COM[0-9]+)$")
                            )
                        ],
                        verbose_name="card port path",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Datetime of the last communication.", verbose_name="last seen"
                    ),
                ),
                (
                    "gd_firmware_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(re.compile("^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$"))
                        ],
                        verbose_name="GardenIQ firmware version",
                    ),
                ),
                (
                    "mp_firmware_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(re.compile("^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$"))
                        ],
                        verbose_name="MicroPython firmware version",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("tag__icontains", "device")),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="base.status",
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
