# Generated by Django 6.0.6 on 2026-07-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "channel",
                "verbose_name_plural": "channels",
            },
        ),
        migrations.CreateModel(
            name="ControllerCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "pin_init_cfg",
                    models.JSONField(
                        default=dict,
                        help_text="Initial configuration for the pins.",
                        verbose_name="pin init configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "controller category",
                "verbose_name_plural": "controller categories",
            },
        ),
        migrations.CreateModel(
            name="SensorCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "pin_init_cfg",
                    models.JSONField(
                        default=dict,
                        help_text="Initial configuration for the pins.",
                        verbose_name="pin init configuration",
                    ),
                ),
                (
                    "unity_value",
                    models.CharField(
                        blank=True,
                        help_text="Unity value of the sensor category (e.g: '°C', '%', 'lux').",
                        max_length=20,
                        verbose_name="unity value",
                    ),
                ),
            ],
            options={
                "verbose_name": "sensor category",
                "verbose_name_plural": "sensor categories",
            },
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "device", "verbose_name_plural": "devices"},
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "pin_number",
                    models.PositiveIntegerField(
                        help_text="The physical pin number on the device.", verbose_name="pin number"
                    ),
                ),
                (
                    "channel_choiced",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choiced_pins",
                        to="hardware.channel",
                        verbose_name="channel",
                    ),
                ),
                (
                    "channels_available",
                    models.ManyToManyField(
                        help_text="Channels that can be assigned to this pin.",
                        related_name="available_pins",
                        to="hardware.channel",
                        verbose_name="available channels",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="hardware.device",
                        verbose_name="device",
                    ),
                ),
            ],
            options={
                "verbose_name": "pin",
                "verbose_name_plural": "pins",
            },
        ),
        migrations.CreateModel(
            name="Controller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="hardware.device",
                        verbose_name="device",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="hardware.controllercategory",
                        verbose_name="controller category",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="hardware.pin",
                        verbose_name="pin",
                    ),
                ),
            ],
            options={
                "verbose_name": "controller",
                "verbose_name_plural": "controllers",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensors",
                        to="hardware.device",
                        verbose_name="device",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensors",
                        to="hardware.pin",
                        verbose_name="pin",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensors",
                        to="hardware.sensorcategory",
                        verbose_name="sensor category",
                    ),
                ),
            ],
            options={
                "verbose_name": "sensor",
                "verbose_name_plural": "sensors",
            },
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(fields=("device", "pin_number"), name="unique_device_pin_number"),
        ),
    ]
