# Generated by Django 5.2.7 on 2025-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("tag", models.SlugField(help_text="A tag of this status. (Like category).", verbose_name="tag")),
                ("color", models.CharField(default="#A2A2A2", max_length=7, verbose_name="color")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
