# Generated by Django 6.0.6 on 2026-07-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "status", "verbose_name_plural": "statuses"},
        ),
    ]
