# Generated by Django 6.0.6 on 2026-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_status_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="is_ready",
            field=models.BooleanField(
                default=True, help_text="Designate whether this object is ready to be used.", verbose_name="is ready"
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="seed_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="The id of the seeder that created this object.",
                null=True,
                unique=True,
                verbose_name="seed id",
            ),
        ),
    ]
