# Generated by Django 5.2.4 on 2025-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, help_text='A slug is a short label for something, containing only letters, numbers, underscores or hyphens.', verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('is_enabled', models.BooleanField(default=True, help_text='Designate whether this object is enabled and will show up in searches by default.', verbose_name='is enabled')),
                ('value_type', models.CharField(choices=[('int', 'integer'), ('float', 'float'), ('str', 'string'), ('bool', 'boolean'), ('list', 'list')], help_text='A value type of a argument.', max_length=5, verbose_name='value type')),
                ('required', models.BooleanField(default=True, help_text='Define if this argument is required or not to the order.', verbose_name='required')),
                ('is_option', models.BooleanField(default=False, help_text='A option is a argument without value like `--verbose`.', verbose_name='is option')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, help_text='A slug is a short label for something, containing only letters, numbers, underscores or hyphens.', verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_enabled', models.BooleanField(default=True, help_text='Designate whether this object is enabled and will show up in searches by default.', verbose_name='is enabled')),
                ('action_type', models.CharField(choices=[('get', 'getter'), ('set', 'setter')], max_length=10, verbose_name='action type')),
                ('arguments', models.ManyToManyField(help_text='All the arguments necessary for the command to work.', related_name='orders', to='orderlg.argument', verbose_name='arguments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
