# Generated by Django 6.0.6 on 2026-07-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_channel_controllercategory_sensorcategory_and_more"),
        ("orderlg", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AddField(
            model_name="order",
            name="controller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="hardware.controller",
                verbose_name="controller",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ctrl_value",
            field=models.CharField(
                blank=True,
                help_text="The control value to set. If `is_toggle_ctrl_value` is True, this field will be ignored.",
                max_length=50,
                null=True,
                verbose_name="control value",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_toggle_ctrl_value",
            field=models.BooleanField(
                default=False,
                help_text="If True, the order will toggle the control value. If False, the order will set the control value to the specified value.",
                verbose_name="is toggle control value",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sensor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="hardware.sensor",
                verbose_name="sensor",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action_type", "get"),
                        models.Q(("sensor__isnull", False), ("controller__isnull", False), _connector="OR"),
                    ),
                    models.Q(("action_type", "set"), ("controller__isnull", False), ("sensor__isnull", True)),
                    _connector="OR",
                ),
                name="check_order_action_type_sensor_controller",
            ),
        ),
    ]
