# Generated by Django 5.2.7 on 2025-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderlg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="argument",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("int", "integer"),
                    ("float", "float"),
                    ("str", "string"),
                    ("bool", "boolean"),
                    ("list", "list"),
                    ("none", "none"),
                ],
                help_text="A value type of a argument.",
                max_length=5,
                verbose_name="value type",
            ),
        ),
    ]
