# Generated by Django 6.0.6 on 2026-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_channel_controllercategory_sensorcategory_and_more"),
        ("orderlg", "0002_alter_order_options_order_controller_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="check_order_action_type_sensor_controller",
        ),
        migrations.AddField(
            model_name="order",
            name="is_ready",
            field=models.BooleanField(
                default=True, help_text="Designate whether this object is ready to be used.", verbose_name="is ready"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="seed_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="The id of the seeder that created this object.",
                null=True,
                unique=True,
                verbose_name="seed id",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("seed_id__isnull", False),
                        ("seed_id__gt", 0),
                        ("is_ready", False),
                        ("controller__isnull", True),
                        ("sensor__isnull", True),
                    ),
                    models.Q(
                        ("action_type", "get"),
                        models.Q(("sensor__isnull", False), ("controller__isnull", False), _connector="OR"),
                    ),
                    models.Q(("action_type", "set"), ("controller__isnull", False), ("sensor__isnull", True)),
                    _connector="OR",
                ),
                name="check_order_action_type_sensor_controller",
            ),
        ),
    ]
